# ATOMKI Common Data Acquisition
#
# (c) 2024 ATOMKI, Debrecen, Hungary
#
# Apache License Version 2.0

# Use the CI's image.
FROM krasznaa/cda-build:ubuntu-16.04-v2

# Set up the command to run when starting the image.
CMD /bin/bash
